

set( CPACK_RPM_PACKAGE_NAME "libxdispatch")
set( CPACK_RPM_PACKAGE_VERSION "${XDISPATCH_VERSION}.${PACKAGE_COMPILER}.${PACKAGE_ARCH}")
set( CPACK_RPM_PACKAGE_LICENSE "${XDISPATCH_LICENSE}")
set( CPACK_RPM_PACKAGE_REQUIRES "glibc, libstdc++45")
set( CPACK_RPM_PACKAGE_ARCHITECTURE "${PACAKGE_ARCH}")


message("-- Configured generator 'RPM'")
set( XDISPATCH_CPACK ${XDISPATCH_CPACK} RPM )
