

install(FILES 
	${CMAKE_CURRENT_SOURCE_DIR}/README.dox 
	${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG.dox 
	${CMAKE_CURRENT_SOURCE_DIR}/LICENSE 
	${CMAKE_CURRENT_SOURCE_DIR}/NOTICE 
	${CMAKE_CURRENT_SOURCE_DIR}/TODO.txt 
		DESTINATION .)

